### ISSUE TITLE
"Cancel" and "Yes" should be translatable

### ISSUE THREAD

**Issue by m4sk1n** [manjaro/manjaro-settings-manager#96]
I don't know why, "Cancel" and "Yes" strings in Manjaro Settings Manager aren't available to translate. It happens when I'm trying to install language packs. Also, name and description of this app should be translatable...

**Comment by prescott66** [comment]
+1

**Comment by scachemaille** [comment]
> I don't know why, "Cancel" and "Yes" strings in Manjaro Settings Manager aren't available to translate.
did you install qt5-translation... which language do you use, because they are translated.

> Also, name and description of this app should be translatable...
you talk about the menu shortcuts? you should check [transiflex project page](https://www.transifex.com/manjarolinux/manjaro-settings-manager/) to see if all your language is translated. and maybe contribute. as I think kirek put them there too recently.

**Comment by m4sk1n** [comment]
@scachemaille
Now I understand :D
I just haven't installed it yet...
But menu shortcut name and description still isn't in Polish (my language). I can't see string for this on Transifex...

**Comment by prescott66** [comment]
I think all strings should be on transifex...in latest stable MSM is more not translatable strings. Maybe POT should be updated.
